export const SET_MEDIA_CONTENT_START = 'SET_MEDIA_CONTENT_START';
export const SET_MEDIA_CONTENT_SUCCEED = 'SET_MEDIA_CONTENT_SUCCEED';
export const SET_MEDIA_CONTENT_FAILED = 'SET_MEDIA_CONTENT_FAILED';