export const SET_MEDIA_CONTENT_START = 'SET_MEDIA_CONTENT_START';
export const SET_MEDIA_CONTENT_SUCCEED = 'SET_MEDIA_CONTENT_SUCCEED';
export const SET_MEDIA_CONTENT_FAILED = 'SET_MEDIA_CONTENT_FAILED';

export const SET_SHOWS_FILTER = 'SET_SHOWS_FILTER';
export const SET_EPISODES_FILTER = 'SET_EPISODES_FILTER';
export const SET_LIST_FILTER = 'SET_LIST_FILTER';
export const SET_GRID_FILTER = 'SET_GRID_FILTER';
